### ISSUE TITLE
epscass.prd-prsn.com API - Not working

### ISSUE THREAD

**Issue by LucyBot-Andrew** [APIs-guru/api-models#10]
Just FYI, it doesn't look like this API is being supported anymore (it is Pearson's OpenClass API - http://code.pearson.com/openclass).

**Comment by IvanGoncharov** [comment]
It actually vise versa. This API spec was updated recently but repo have outdated version.
I can't updated it because new version is broken and it will stop all deployment.
I working on the solution right now.
Following API in this state right now:
        daisycon.com/1.0.0/swagger.json
        likefolio.com/v0/swagger.json
        prd-prsn.com/1.0.0/swagger.json
        uploady.com/v1-beta/swagger.json
        zoomconnect.com/1/swagger.json
I will try to solve this problem in next couple of days.

**Comment by IvanGoncharov** [comment]
prd-prsn.com fixed in 3f44f84
