### ISSUE TITLE
APIMATIC API Transformer API

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/api-models#57]
Hi Ivan, another API spec for you if it meets your criteria.

https://raw.githubusercontent.com/Mermade/open_api_specifications/master/APIMATIC%20API%20Transformer/swagger.json

It is particularly interesting as it exposes an API which can convert several API spec formats to Swagger, including Postman collections.

Mike

PS the other specs in this repository I'm still working on.

**Comment by IvanGoncharov** [comment]
> another API spec for you if it meets your criteria.

It public, useful and have active maintainer :+1: 
The same note as #58, please fix `x-logo`.

**Offtopic + IMHO**: API Transformer is really good addition to collection, just my thoughts on a topic:

> It is particularly interesting as it exposes an API which can convert several API spec formats to Swagger, including Postman collections.

Initially, I search for convert to using for this project and `API Transformer` was one of the options.
The big problem with it's not an open-source so I can't debug it or contribute fixes.

So together with Lucybot I work on:
https://github.com/lucybot/api-spec-converter
Currently it only support Swagger as output format.

> including Postman collections.

Postman has official converter:
https://github.com/postmanlabs/swagger2-to-postman

And I plan to integrate it into `api-spec-converter` since I plan to add postman button for each API:
https://www.getpostman.com/docs/run_button
I contacted Postman guys and waiting for them to release public API for Postman Cloud.

**Comment by MikeRalphson** [comment]
Thanks will fix x-logo. 

Very interesting stuff. What I thought was useful was converting **from **Postman collections **to **Swagger, say when all that is provided for an API is a Run in Postman button.

I find it is quite a nice workflow to start documenting an API with Postman operations, then export to Swagger to finish off.

**Comment by MikeRalphson** [comment]
x-logo fixed.

**Comment by IvanGoncharov** [comment]
> I find it is quite a nice workflow to start documenting an API with Postman operations, then export to Swagger to finish off.

IMHO manual describing of API spec should be used only as last resort if any other attempts are failed.
Take a look at this scrapping tool: https://github.com/bobby-brennan/scrape-to-swagger
But I will gladly except specs from any source if it will have an active maintainer.
